//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDuLich
{
    using System;
    using System.Collections.Generic;
    using DAL;

    public partial class CHIPHI
    {
        public string MACHIPHI { get; set; }
        public string MADOAN { get; set; }
        public Nullable<double> SOTIEN { get; set; }
    
        public virtual LOAICHIPHI LOAICHIPHI { get; set; }
        public virtual DOANDULICH DOANDULICH { get; set; }

        public string TENLOAICHIPHI
        {
            get { return LOAICHIPHI.TENLOAICHIPHI; }
        }

        public string THANHTIEN
        {
            get { return DinhDanhTien((double)SOTIEN); }
        }

        public string DinhDanhTien(double Tien)
        {
            return string.Format("{0:#,##0}", Tien);
        }

        public List<CHIPHI> getChiPhi(string MaChiPhi)
        {
            return new DAL_ChiPhi().GetChiPhi(MaChiPhi);
        }

        public bool Insert(CHIPHI ChiPhi)
        {
            return new DAL_ChiPhi().Insert(ChiPhi);
        }

        public bool Update(CHIPHI ChiPhiMoi)
        {
            return new DAL_ChiPhi().Update(ChiPhiMoi);
        }

        public bool Delete(CHIPHI ChiPhi)
        {
            return new DAL_ChiPhi().Delete(ChiPhi);
        }
    }
}
