//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDuLich
{
    using System;
    using System.Collections.Generic;
    using DAL;
    
    public partial class CHITIETDOAN
    {
        public string MADOAN { get; set; }
        public string MAKH { get; set; }
        public string VAITROKH { get; set; }
    
        public virtual DOANDULICH DOANDULICH { get; set; }
        public virtual KHACH KHACH { get; set; }

        public string TENKHACHHANG
        {
            get { return KHACH.HOTEN; }
        }

        public List<CHITIETDOAN> getChiTietDoan(string MaDoan)
        {
            return new DAL_ChitTietDoan().GetChiTiet(MaDoan);
        }

        public bool Insert(CHITIETDOAN ChiTietDoan)
        {
            return new DAL_ChitTietDoan().Insert(ChiTietDoan);
        }

        public bool Update(CHITIETDOAN ChiTietDoanMoi)
        {
            return new DAL_ChitTietDoan().Update(ChiTietDoanMoi);
        }

        public bool Delete(CHITIETDOAN ChiTietDoan)
        {
            return new DAL_ChitTietDoan().Delete(ChiTietDoan);
        }
    }
}
