//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDuLich
{
    using System;
    using System.Collections.Generic;
    using DAL;
    
    public partial class DIADIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIADIEM()
        {
            this.CHITIETTOURs = new HashSet<CHITIETTOUR>();
        }
    
        public string MADIADIEM { get; set; }
        public string TENDIADIEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETTOUR> CHITIETTOURs { get; set; }

        public List<DIADIEM> GetAll()
        {
            return new DAL_DiaDiem().GetAll();
        }

        public bool Insert(DIADIEM DiaDiem)
        {
            return new DAL_DiaDiem().Insert(DiaDiem);
        }

        public bool Update(DIADIEM DiaDiemCu, DIADIEM DiaDiemMoi)
        {
            return new DAL_DiaDiem().Update(DiaDiemCu, DiaDiemMoi);
        }

        public bool Delete(DIADIEM DiaDiem)
        {
            return new DAL_DiaDiem().Delete(DiaDiem);
        }
    }
}
