//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDuLich
{
    using System;
    using System.Collections.Generic;
    using DAL;
    
    public partial class DOANDULICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOANDULICH()
        {
            this.CHIPHIs = new HashSet<CHIPHI>();
            this.CHITIETDOANs = new HashSet<CHITIETDOAN>();
        }
    
        public string MADOAN { get; set; }
        public string MATOUR { get; set; }
        public Nullable<System.DateTime> NGAYKHOIHANH { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public double DOANHTHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHIPHI> CHIPHIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDOAN> CHITIETDOANs { get; set; }
        public virtual TOURDULICH TOURDULICH { get; set; }
        public virtual NOIDUNG NOIDUNG { get; set; }

        public string TENGOI
        {
            get { return TOURDULICH.TENGOI; }
        }

        public string GIATIEN
        {
            get { return DinhDanhTien((double)DOANHTHU); }
        }

        public List<DOANDULICH> GetAll()
        {
            return new DAL_Doan().GetAll();
        }

        public bool Insert(DOANDULICH Doan)
        {
            return new DAL_Doan().Insert(Doan);
        }

        public bool Update(DOANDULICH DoanMoi)
        {
            return new DAL_Doan().Update(DoanMoi);
        }

        public bool Delete(DOANDULICH Doan)
        {
            return new DAL_Doan().Delete(Doan);
        }

        public string DinhDanhTien(double Tien)
        {
            return string.Format("{0:#,##0}", Tien);
        }
    }
}
