//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDuLich
{
    using System;
    using System.Collections.Generic;
    using DAL;
    
    public partial class GIATOUR
    {
        public string MAGIA { get; set; }
        public string MATOUR { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<System.DateTime> TG_BATDAU { get; set; }
        public Nullable<System.DateTime> TG_KETTHUC { get; set; }
    
        public virtual TOURDULICH TOURDULICH { get; set; }

        public string GIATIEN
        {
            get { return DinhDanhTien((double)THANHTIEN); }
        }

        public string TENGOI
        {
            get { return TOURDULICH.TENGOI; }
        }

        public string DACDIEM
        {
            get { return TOURDULICH.DACDIEM; }
        }

        public string TENLOAIHINH
        {
            get { return TOURDULICH.LOAIHINHDULICH.TENLOAIHINH; }
        }

        public List<GIATOUR> GetAll()
        {
            return new DAL_GiaTour().GetAll();
        }

        public List<GIATOUR> GetGiaTour(string MaTour)
        {
            return new DAL_GiaTour().GetGiaTour(MaTour);
        }

        public string DinhDanhTien(double Tien)
        {
            return string.Format("{0:#,##0}", Tien);
        }

        public bool Insert(GIATOUR Gia)
        {
            return new DAL_GiaTour().Insert(Gia);
        }

        public bool Update(GIATOUR GiaMoi)
        {
            return new DAL_GiaTour().Update(GiaMoi);
        }

        public bool Delete(GIATOUR Gia)
        {
            return new DAL_GiaTour().Delete(Gia);
        }
    }
}
