//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDuLich
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTOURDULICHEntities : DbContext
    {
        public QUANLYTOURDULICHEntities()
            : base("name=QUANLYTOURDULICHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHIPHI> CHIPHIs { get; set; }
        public virtual DbSet<CHITIETDOAN> CHITIETDOANs { get; set; }
        public virtual DbSet<CHITIETTOUR> CHITIETTOURs { get; set; }
        public virtual DbSet<DIADIEM> DIADIEMs { get; set; }
        public virtual DbSet<DOANDULICH> DOANDULICHes { get; set; }
        public virtual DbSet<GIATOUR> GIATOURs { get; set; }
        public virtual DbSet<KHACH> KHACHes { get; set; }
        public virtual DbSet<LOAICHIPHI> LOAICHIPHIs { get; set; }
        public virtual DbSet<LOAIHINHDULICH> LOAIHINHDULICHes { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NOIDUNG> NOIDUNGs { get; set; }
        public virtual DbSet<PHANBONHANVIEN> PHANBONHANVIENs { get; set; }
        public virtual DbSet<TOURDULICH> TOURDULICHes { get; set; }
    }
}
