//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDuLich
{
    using System;
    using System.Collections.Generic;
    using DAL;

    public partial class NOIDUNG
    {
        public string MADOAN { get; set; }
        public string HANHTRINH { get; set; }
        public string KHACHSAN { get; set; }
    
        public virtual DOANDULICH DOANDULICH { get; set; }

        public NOIDUNG GetNoiDung(string MaDoan)
        {
            return new DAL_NoiDung().GetNoiDung(MaDoan);
        }

        public bool Insert(NOIDUNG NoiDung)
        {
            return new DAL_NoiDung().Insert(NoiDung);
        }

        public bool Update(NOIDUNG NoiDungMoi)
        {
            return new DAL_NoiDung().Update(NoiDungMoi);
        }

        public bool Delete(NOIDUNG NoiDung)
        {
            return new DAL_NoiDung().Delete(NoiDung);
        }
    }
}
